Add IOG contracts
runtimeverification/plutus-core-semantics pull request #290
Opened 2022-08-19 17:15 UTC by ChristianoBraga

- Milestone 2 requires the execution and verification of ERC20-like
contracts in KPlutus. The closest element in Cardano is a native token
minting policy. Milestone 3 is set to a best effort audit, using
KPlutus, of the DJED protocol: an algorithmic stablecoin dApp.

- This commit adds directory `IOG-contracts`. Under this directory
  there are 2 subdirectories: `native-tokens` and
  `stablecoin`. Directory `native-tokens` has two contracts and some
  files to generate UPLC code from their minting policies and traces
  of their execution. Directory `stablecoin` has one contract, an
  implementation of MiniDJED, a DJED prototype, and similar scripts
  for UPLC code generation.

- There are `README.md` files under `IOG-contracts` and for each
  subdirectory explaining their contents and how to generate UPLC code
  from them.

2022-08-23 20:07 UTC, PetarMax requested changes

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/README.md
> +`nix-shell` _from `plutus-apps`_, and this is very important. Only
```suggestion
`nix-shell` _from `plutus-apps`_. This is _very important_. Only
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/README.md
> +then the cabal commands can be executed from within the `nix-shell`.
```suggestion
then can the cabal commands be executed from within the `nix-shell`.
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/README.md
> +
```suggestion
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/README.md
> +They prevent simplifications to take place and their absence may
```suggestion
They prevent simplifications from taking place and their absence may
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/README.md
> +produce UPLC incorrect.
```suggestion
produce incorrect UPLC code.
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/README.md
> +The `TypeApplications` language extension is necessary to the UPLC code
```suggestion
The `TypeApplications` language extension is necessary for the UPLC code
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/stablecoin/README.md
> +This contract implements MiniDJED stable coin as described [here](https://iohk.io/en/research/library/papers/djed-a-formally-verified-crypto-backed-pegged-algorithmic-stablecoin/). It's
```suggestion
This contract implements the MiniDJED stablecoin, as described [here](https://iohk.io/en/research/library/papers/djed-a-formally-verified-crypto-backed-pegged-algorithmic-stablecoin/). It is   
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/stablecoin/README.md
> +part of `plutus-use-cases` in `plutus-apps` [repo](https://github.com/input-output-hk/plutus-apps). (Just for completeness, there exists a prototype for DJED in Scala [here](https://github.com/input-
```suggestion
part of `plutus-use-cases` in `plutus-apps` [repo](https://github.com/input-output-hk/plutus-apps) (for completeness, there exists a prototype for DJED in Scala [here](https://github.com/input-output-hk/djed-stablecoin-prototype)).
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/stablecoin/README.md
> +1. Follow instructions at issue [#285](https://github.com/runtimeverification/plutus-core-semantics/issues/285) to get `nix`, `plutus` and `plutus-apps` up and running in your system, if necessary.
```suggestion
1. Follow instructions in issue [#285](https://github.com/runtimeverification/plutus-core-semantics/issues/285) to get `nix`, `plutus` and `plutus-apps` up and running in your system, if necessary.
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/stablecoin/README.md
> +   This will generate file `out_scripts/stablecoinPolicy.uplc.noindices`
```suggestion
   This will generate the `out_scripts/stablecoinPolicy.uplc.noindices` file,
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/native-tokens/README.md
> +tokens. Contract `Free.hs` implements the trivial policy that
```suggestion
tokens. The contract `Free.hs` implements the trivial policy that
```

2022-08-23 20:07 UTC, PetarMax commented on IOG-contracts/native-tokens/README.md
> +generates true to every input. Contract `NFT.hs` is a more elaborated
```suggestion
generates true to every input, whereas the `NFT.hs` contract is a more elaborate
```

2022-08-23 20:20 UTC, SchmErik commented on IOG-contracts/native-tokens/README.md
> +2. Change to `plutus-semantics/native-tokens/native-tokens`.
this should be `plutus-semantics/IOG-contracts/native-tokens/native-tokens`

2022-08-23 20:20 UTC, SchmErik commented on IOG-contracts/stablecoin/README.md
> +2. Change to `plutus-semantics/stablecoin/stablecoin`.
this should be `plutus-semantics/IOG-contracts/stablecoin/stablecoin`

2022-08-23 21:36 UTC, SchmErik approved these changes
Approved but please address the 2 typos that I've written in the comments..

2022-08-23 21:37 UTC, SchmErik commented
nevermind, I saw that they've been addressed.

2022-08-24 09:15 UTC, PetarMax approved these changes

2022-08-24 09:18 UTC, merged