Setup CI on new Jenkins
runtimeverification/plutus-core-semantics pull request #48
Opened 2021-11-29 19:34 UTC by ehildenb

2021-11-29 22:15 UTC, SchmErik approved these changes

2021-11-30 17:02 UTC, dwightguth requested changes
some of the copy-paste needs to be audited, but overall it seems okay

2021-11-30 17:02 UTC, dwightguth commented on kplutus
> +[[ ! "$run_command" =~ klab*   ]] || backend='java'
this seems like it should be removed

2021-11-30 17:02 UTC, dwightguth commented on kplutus
> +[[ ! "$run_command" == 'prove' ]] || backend='java'
let's make this default to haskell

2021-12-01 16:42 UTC, ehildenb commented on Jenkinsfile
> +            stage('Conformance') { steps { sh 'echo test-conformance' } }
Yeah, it's just a placeholder.

2021-12-01 16:47 UTC, ehildenb commented on Makefile
> +# Settings
The settings here are generic and will be needed for builds and installs, so would rather have it in place (same with kplutus script) to make reviews of changes to it more incremental.

But I stripped out a bunch of stuff that I missed in the first pass.

2021-12-01 16:47 UTC, ehildenb commented on kplutus
> +[[ ! "$run_command" =~ klab*   ]] || backend='java'
Done

2021-12-01 16:48 UTC, ehildenb commented on LICENSE
> +Copyright (c) 2010-2021, K Team
Done.

2021-12-01 17:04 UTC, dwightguth approved these changes

2021-12-01 18:43 UTC, merged