Adding builtins
runtimeverification/plutus-core-semantics pull request #82
Opened 2022-01-10 14:50 UTC by ChristianoBraga

Added the following builtins: addInteger, multiplyInteer, subtractInteger, divideInteger, lessThanInteger.

2022-01-10 14:58 UTC, ChristianoBraga commented
The force.uplc test in tests/simple is failing because the semantics changed. This is making jenkins unhappy.

2022-01-10 18:59 UTC, SchmErik requested changes
Over all looks good! I saw that there were several tabs so please go through uplc.md and fix them. Also, please check out my question regarding the tests/failing file

2022-01-10 18:59 UTC, SchmErik commented on tests/failing
> +tests/simple/error.uplc
out of curiosity, why is this test listed as a failing test? I see that there is an expected output file and it looks good to me. What happens if this line is removed?

2022-01-10 18:59 UTC, SchmErik commented on uplc.md
> +			 | "bytestring"
I see tabs here. Please replace tabs with spaces

2022-01-10 18:59 UTC, SchmErik commented on uplc.md
> +			 | "False"
I see tabs here. Please replace tabs with spaces

2022-01-10 18:59 UTC, SchmErik commented on uplc.md
> +			 | "divideInteger"
I see tabs here. Please replace tabs with spaces

2022-01-10 18:59 UTC, SchmErik commented on uplc.md
> +		  | "#SUM"
I see tabs here. Please replace tabs with spaces

2022-01-10 18:59 UTC, SchmErik commented on uplc.md
> +		 | "(" "builtin" BuiltinName TermList ")"// builtin
I see tabs here. Please replace tabs with spaces

2022-01-10 18:59 UTC, SchmErik commented on uplc.md
> +		 | "[" AClosure "_]"
I see tabs here. Please replace tabs with spaces

2022-01-17 22:33 UTC, SchmErik approved these changes
looks good to me

2022-01-17 22:42 UTC, merged